---
- name: Config new machine
  hosts: localhost
  become: yes
  gather_facts: yes

  vars: 
    PACKAGES: 
    - "vim"
    - "ranger"
    - "zsh"
    PACKAGES_ARCH: 
    - "cronie"
    - "python-pip"

  tasks:
    - name: install packages (arch)
      package:
        name: "{{ PACKAGES + PACKAGES_ARCH }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    - name: install zsh plugins
      block: 
      - name: zsh-autosuggestions
        git:
          repo: https://github.com/zsh-users/zsh-autosuggestions
          dest: /home/simon/.oh-my-zsh/custom/plugins/zsh-autosuggestions

      - name: zsh-syntax-highlighting
        git:
          repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
          dest: /home/simon/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting 