---
- name: Config new machine
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

  vars: 
    PACKAGES: 
    - "vim"
    - "ranger"
    PACKAGES_ARCH: 
    - "cronie"
    - "python-pip"

  tasks:
    - name: install packages (arch)
      package:
        name: "{{ PACKAGES + PACKAGES_ARCH }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"