---
- name: Config new machine
  hosts: localhost
  become: yes
  become_user: simon
  gather_facts: yes

  vars: 
    PACKAGES: 
    - "vim"
    - "ranger"
    - "zsh"
    PACKAGES_ARCH: 
    - "cronie"
    - "python-pip"
    - "zsh-autosuggestions" # zsh plugin
    - "zsh-syntax-highlighting" # zsh plugin

  tasks:
    - name: install packages (arch)
      package:
        name: "{{ PACKAGES + PACKAGES_ARCH }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    - name: debug $ZSH_CUSTOM variable
      debug:
        msg: "{{ lookup('env', 'HOME') }}"