---
- name: Config new machine
  hosts: localhost
  become: yes
  become_method: sudo
  become_user: root
  gather_facts: yes

  vars: 
    PACKAGES: 
    - "vim"
    - "ranger"
    - "zsh"
    PACKAGES_ARCH: 
    - "cronie"
    - "python-pip"
    - "zsh-autosuggestions" # zsh plugin

  tasks:
    - name: install packages (arch)
      package:
        name: "{{ PACKAGES + PACKAGES_ARCH }}"
        state: present
        update_cache: yes
      when: ansible_os_family == "Archlinux"

    - name: Set zsh as default shell for simon
      user:
        name: simon
        shell: /bin/zsh
    - name: Set zsh as default shell for root
      user:
        name: root
        shell: /bin/zsh