---
- name: Config new machine
  hosts: localhost
  become: yes
  gather_facts: yes

  tasks:
    - name: install packages
      block: 
      - name: everywhere instal
        package:
          name: 
          - "vim"
          - "ranger"
          - "zsh"
          - "bpytop"
          - "flameshot"
          - "copyq"
          state: present
          update_cache: yes

      - name: everywhere remove
        package:
          name: 
          - "clipit"
          state: absent

      - name: arch install
        package:
          name: 
          - "cronie"
          - "python-pip"
          - "yay"
          - "micro"
          - "libinput-gestures"
          - "rofimoji"
          - "knotes"
          state: present
          update_cache: yes
        when: ansible_os_family == "Archlinux"

    - name: install zsh plugins
      block: 
      - name: zsh-autosuggestions
        git:
          repo: https://github.com/zsh-users/zsh-autosuggestions
          dest: /home/simon/.oh-my-zsh/custom/plugins/zsh-autosuggestions

      - name: zsh-syntax-highlighting
        git:
          repo: https://github.com/zsh-users/zsh-syntax-highlighting.git
          dest: /home/simon/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

    - name: Make sure that directory /tmp/yay is accessible
      file:
        path: /tmp/yay
        state: directory
        mode: 0755
        owner: simon
        group: simon
      tags: last

    - name: Download apps and configuration them
      block: 
      - name: make directory for images
        file:
          path: /home/simon/Documents/Linux/Apps/
          state: directory
          mode: 0755
          owner: simon
          group: simon

      - name: espanso
        block:
        - name: Download app
          get_url:
            url: https://github.com/federico-terzi/espanso/releases/download/v2.1.7-beta/Espanso-X11.AppImage
            dest: /home/simon/Documents/Linux/Apps/espanso.AppImage
            mode: 0755
            owner: simon
            group: simon

        - name: start service
          shell: /home/simon/Documents/Linux/Apps/espanso.AppImage service register &&  /home/simon/Documents/Linux/Apps/espanso.AppImage start || true
          become_user: simon

    - name: libinput-gestures - Add yourself (simon) to group input
      user:
        name: simon
        groups: input
        append: yes

    - name: ranger - instal plugin ranger-archives
      git:
        repo: https://github.com/maximtrp/ranger-archives.git
        dest: /home/simon/.config/ranger/plugins/ranger-archives

    - name: gromit-mpx - install via "yay"
      shell: "yay -S --noconfirm --needed --cleanafter -y gromit-mpx"
      become: yes
      become_user: root
      tags: last